<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Entity\Pomm\TestRulerz\PublicSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Players
 *
 * Structure class for relation public.players.
 *
 * Class and fields comments are inspected from table and fields comments.
 * Just add comments in your database and they will appear here.
 *
 * @see http://www.postgresql.org/docs/9.0/static/sql-comment.html
 * @see RowStructure
 */
class Players extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     */
    public function __construct()
    {
        $this
            ->setRelation('public.players')
            ->setPrimaryKey(['pseudo'])
            ->addField('pseudo', 'varchar')
            ->addField('group_id', 'int4')
            ->addField('fullname', 'varchar')
            ->addField('gender', 'bpchar')
            ->addField('age', 'int4')
            ->addField('points', 'int4')
            ;
    }
}
